import { FlatCompat } from "@eslint/eslintrc";

const compat = new FlatCompat({ baseDirectory: import.meta.dirname });

export default [
  ...compat.extends("next/core-web-vitals", "next/typescript"),
  {
    // next-env.d.ts is a Next.js-generated file (gitignored; regenerated by
    // `next dev`/`next build`; its own header says "should not be edited") —
    // lint-ignored like ink-icons.generated.ts, not "fixed".
    ignores: [".next/**", "node_modules/**", "components/ink-icons.generated.ts", "next-env.d.ts"],
  },
];
